[features]
seeds = false
[programs.localnet]
demo_swap_program = "AGCxcT9XB4G8fWgrFypvJTn7XENcKigshSDFp7veNkpx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/thuongthai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
